### ISSUE TITLE
Could you please add a Google Analytics input box to customizer?

### ISSUE THREAD

**Issue by cnyyk** [FameThemes/onepress#116]
Could you please add a Google Analytics(and others) input box to customizer below custom css?

This box will write the analytics code to footer(before body close)

**Comment by KienTrong** [comment]
I want to do that at the beginning but the reviewer admin at wp.org won't allow that cause it's plugin territory.

**Comment by DanDawson** [comment]
I wonder if the wp.org reviewer admin would allow you to just add a box for "custom code" or "custom javascript" where we could input the analytics tracking code. It would be so convenient to just drop to code in to customizer rather than installing an additional plugin.

But either way, great theme!

**Comment by KienTrong** [comment]
Hi Dan, any tracking codes should be in plugin because when users switch to other theme, these code will lose. And the theme reviewer won't allow us to put these setting to Customizer :)

**Comment by DanDawson** [comment]
That makes sense, thanks for the additional details.  I knew I had other themes that built it right in (Headway Themes) but on further review, they aren't in the WordPress Theme Directory, so that explains why!  

Keep up the great work :-)
